
version: 2
updates:
  - package-ecosystem: "pip" # f√ºr Pyhton
    directory: "/" # Zeigt das Requirement in der Root Repository ist bei Unterornder ensprechend angeben
    schedule:
      interval: "weekly"
